# -*- coding: utf-8 -*-
"""SRH DATA ANALYSIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHK8V0vJMlx8BtpLS-Rie21xeUReidSH
"""

# Problem Statement : The decision by the Management of Sunrisers Hyderabad of replacing David Warner with 
# Kane William was fair

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# statictics of David Warner
dw=pd.read_excel('DATA ANALYSIS.xlsx',sheet_name='david warner')
dw

dw.drop(['YEAR','MATCHES PLAYED','RUNS','AVERAGE','STRIKE RATE'],axis=1,inplace=True)

#normalised data of davivd warner
dw

#statictics of Kane Williamson
kw=pd.read_excel('DATA ANALYSIS.xlsx',sheet_name='kane williamson')
kw

kw.drop(['YEAR','MATCHES PLAYED','TOTAL RUNS','AVERAGE','STRIKE RATE'],axis=1,inplace=True)

#normalised data of kane williamson
kw

#1.  PERFORMANCE

#finding corelation in david warners stats
dw.corr()

#finding correlation in kane williamsons stats
kw.corr()

# on finding the coreleation btw various parameters in our data we observe there is a relation between number of matches
#and the runs scored by the player
#In case of David Warner the corelation is 0.779525
#In case of Kane Williamson the corelation is 0.925281 (strongly co related)(positive corelation)
# Implies more number of matches higher the runs

x=sns.relplot(data = dw, x = 'NORMALISED MATCHES', y = 'NORMALISED RUNS', kind = 'line')
y=sns.relplot(data = kw, x = 'NORMALISED MATCHES', y = 'NORMALISED RUNS', kind = 'line')
x.set(title = "DAVID WARNER")
y.set(title = "KANE WILLIAMSON")
plt.show()

#David Warner's performance is not so consistent
#Kane willison performance is an increasing curve 
# Conclusion : Kane williamson is much more reliable compared to David Warner

2.# FLEXIBILITY IN BATTING POSITION

#DAVID WARNER =ALWAYS OPENER
#KANE WILLIAMSON = FLEXIBLE BETWEEN 1 DOWN AND 2 DOWN

#dwp refers to scores of david warners(opener)
#kw1 refers to the scores of Kane Williamson (1 down)
#kw2 refers to the scores of Kane williamson(2 down)

dwp=np.array([57,6,37,36,54,3,2,17,8,66,35,4,9,48,52,60,28,45,36,6])
kw1=np.array([20,66,16])
kw2=np.array([26,67,50,8,11,57,22,20,3,9,41])

dwp

np.average(dwp)

kw1

np.average(kw1)

kw2

np.average(kw2)



#looking at the original batting position 
#david warner opener= average runs of 30.45
#kane williamson with batting position of 1 down average=34
#kane williamson with batting position of 2 down averge =28.54 
#Implies Kane williamson is flexible in terms of batting position where as david warner is not

#3.#OBSERVING TEAMS WIN/LOSS  TREND IN THE YEARS 2020,2019,2018 AND COMPARING THAT WITH 2021
  #TREND WILL BE OBSERVED BASED ON FIRST 7 MATCHES AS SRH HAS PLAYED ONLY 7 MATCHES IN 2021 AND THERE 
  #WAS A CAPTAIN CHANGE IN THIS PERIOD
  #(TREND BEFORE 2018 WAS NOT CONSIDERED AS THAT YEAR THERE WAS A BAN ON A TEAM WHICH LED TO FORMATION OF ANOTHER TWO TEAMS)

stats21=pd.read_excel('DATA ANALYSIS.xlsx',sheet_name='2021')
stats21
#david warner captain



stats20=pd.read_excel('DATA ANALYSIS.xlsx',sheet_name='2020')
stats20
#david warner captain

stats19=pd.read_excel('DATA ANALYSIS.xlsx',sheet_name='2019')
stats19
#kane williamson captain

stats18=pd.read_excel('DATA ANALYSIS.xlsx',sheet_name='2018')
stats18
#kane william captain

a=sns.relplot(data = stats21, x = 'MATCH NUMBER', y = 'RESULT', kind = 'line')
b=sns.relplot(data = stats20, x = 'MATCH NUMBER', y = 'RESULT', kind = 'line')
c=sns.relplot(data = stats19, x = 'MATCH NUMBER', y = 'RESULT', kind = 'line')
d=sns.relplot(data = stats18, x = 'MATCH NUMBER', y = 'RESULT', kind = 'line')
a.set(title = "YEAR 2021 CAPTAIN :DAVID WARNER")
b.set(title = "YEAR 2020 CAPTAIN :DAVID WARNER")
c.set(title = "YEAR 2019 CAPTAIN :KANE WILLIAMSON")
d.set(title = "YEAR 2018 CAPTAIN :KANE WILLIAMSON")
plt.show()

#observation from the graphs
#2021 follows a trend of continuous losses that is continous loss ,a sudden win and continuous loss that is L L L W L L L
#2020 (david warner captain) the graph follows a trend of  L L W W L W L (THERE IS NOT ANY CONTINUOUS LOSS OR WINS)
#2019 (Kane williamson captain) the graph follows a trend of L W W W L L L (THERE IS TREND OF CONTINUOUS WINS AND CONTINUOUS LOSS)
#2018(Kane williamson captain)the graph follows a trend of W W W L L W W (THERE IS A TREND OF CONTINUOUS WINS FOLLWE BY CONTINUOUS LOSS)

#FROM THIS GRAPHS IT IS EVIDENT THAT KANE WILLIAMSON IS BETTER AT DEALING WITH SITUATIONS THAT FOLLOW A CONTINUOS PATTERN OF EITHER WINS 
#OR LOSSES

#Observation 2 from this trend (THEORETICAL APPROACH)
# In the year 2020 ,2019,2018 all the years sunrisers hyderabad qualifed for the qualifiers 
#it is observed that in all these years in their 1st 7 wins they they won alteat 3 matchs i.e 42.85% of the matches
#in the year 2021 they won 1 match out of their 7 matches i.e 14.28% of the matches
#implies there has to be a change in the team 
#CONSTRAINS:ONLY 4 FOREIGNERS ARE ALLOWED IN THE TEAM.
#HAVING TWO OVERSEAS BATSMEN CAN DISTURB THE TEAM BALANCE.
#HENCE CHOOSING ONE AMONG DAVID AND KANE IS VITAL 
#AS KANE WILLIAMSON HAS BETTER STATISTICS IN DEALING WITH THIS SITUATION IT WAS RIGHT TO CHOOSE HIS AS THE CAPTAIN)

"""# New Section"""